taxprofiler/taxpasta

src/taxpasta/application/service/standard_profile_writer.py, src/taxpasta/infrastructure/application/__init__.py, src/taxpasta/infrastructure/application/application_service_registry.py, src/taxpasta/infrastructure/application/sample_etl_application.py, src/taxpasta/infrastructure/application/standard_profile_file_format.py, src/taxpasta/infrastructure/application/standard_profile_writer/__init__.py, src/taxpasta/infrastructure/application/standard_profile_writer/arrow_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/csv_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/ods_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/tsv_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/xlsx_standard_profile_writer.py, src/taxpasta/infrastructure/cli/__init__.py, src/taxpasta/infrastructure/cli/merge.py, src/taxpasta/infrastructure/cli/standardise.py, tests/system/cli/conftest.py, tests/system/cli/test_taxpasta_merge.py, tests/system/cli/test_taxpasta_standardise.py, tox.ini
=> Create `taxpasta standardise` command

.github/workflows/cron.yml, .github/workflows/main.yml, tox.ini
=> chore: enable Python 3.11

setup.cfg, src/taxpasta/infrastructure/application/application_service_registry.py, src/taxpasta/infrastructure/application/standard_profile_writer/parquet_standard_profile_writer.py, src/taxpasta/infrastructure/application/table_reader/parquet_table_reader.py, src/taxpasta/infrastructure/application/table_reader_file_format.py, src/taxpasta/infrastructure/application/tidy_observation_table_file_format.py, src/taxpasta/infrastructure/application/tidy_observation_table_writer/parquet_table_writer.py, src/taxpasta/infrastructure/application/wide_observation_table_file_format.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/parquet_wide_observation_table_writer.py
=> feat: enable reading & writing Parquet files

docs/contributing/supporting_new_profiler.md, docs/supported_profilers/index.md
Not sure when/how that happened.
=> docs: fix the links to source code

src/taxpasta/infrastructure/application/krakenuniq/krakenuniq_profile.py, src/taxpasta/infrastructure/application/krakenuniq/krakenuniq_profile_reader.py, tests/data/krakenuniq/test3.krakenuniq.report.txt, tests/integration/test_krakenuniq_etl.py, tests/unit/infrastructure/application/bracken/test_bracken_profile_reader.py, tests/unit/infrastructure/application/centrifuge/test_centrifuge_profile_reader.py, tests/unit/infrastructure/application/diamond/test_diamond_profile_reader.py, tests/unit/infrastructure/application/kaiju/test_kaiju_profile_reader.py, tests/unit/infrastructure/application/kraken2/test_kraken2_profile_reader.py, tests/unit/infrastructure/application/krakenuniq/test_krakenuniq_profile_reader.py, tests/unit/infrastructure/application/megan6/test_megan6_profile_reader.py, tests/unit/infrastructure/application/motus/test_motus_profile_reader.py
This PR attempts to fix the bug from different versions of krakenuniq.
=> Fix bug in krakenuniq

README.md, docs/index.md
=> docs: expand about section and add to main readme

.github/CONTRIBUTING.md, .readthedocs.yaml, README.md, docs/contributing/index.md, docs/index.md, docs/requirements.txt, pyproject.toml, tox.ini
=> Document optional dependencies

CHANGELOG.md, src/taxpasta/__init__.py, tests/conftest.py, tests/system/cli/conftest.py, tests/unit/test_version.py
As commented on [Slack](https://nfcore.slack.com/archives/C031QH57DSS/p1678612907184599?thread_ts=1678611295.970749&cid=C031QH57DSS).
=> fix: correctly set the version according to hatch-vcs

CHANGELOG.md, src/taxpasta/infrastructure/application/bracken/bracken_profile.py, tests/data/bracken/2611_se-ERR5766174-db1_S_invalid.tsv, tests/unit/infrastructure/application/bracken/test_bracken_profile.py
=> fix: increase the tolerance when comparing floats

README.md, docs/commands/merge.md, docs/commands/standardise.md, docs/how-tos/how-to-add-names.md, docs/tutorials/getting-started.md, docs/tutorials/tutorial_python_snippets.md, docs/tutorials/tutorial_python_snippets.qmd, docs/tutorials/tutorial_r_snippets.qmd
=> Documentation: minor typo fixes and phrasing tweaks

CHANGELOG.md, src/taxpasta/domain/model/tidy_observation_table.py, src/taxpasta/domain/model/wide_observation_table.py, src/taxpasta/domain/service/sample_merging_service.py, src/taxpasta/infrastructure/application/bracken/bracken_profile.py, src/taxpasta/infrastructure/application/centrifuge/centrifuge_profile.py, src/taxpasta/infrastructure/application/kaiju/kaiju_profile.py, src/taxpasta/infrastructure/application/kraken2/kraken2_profile.py, src/taxpasta/infrastructure/application/metaphlan/metaphlan_profile.py, tests/data/bracken/2611_se-ERR5766174-db1_S_invalid.tsv, tests/data/kraken2/2611_se-ERR5766174-db1-invalid.kraken2.report.txt, tests/data/kraken2/2612_pe-ERR5766176-db1-invalid.kraken2.report.txt, tests/unit/infrastructure/application/centrifuge/test_centrifuge_profile.py, tests/unit/infrastructure/application/kaiju/test_kaiju_profile.py, tests/unit/infrastructure/application/kraken2/test_kraken2_profile.py, tests/unit/infrastructure/application/megan6/test_megan6_profile.py
=> refactor: generally allow 1% tolerance of compositionality

CHANGELOG.md, docs/contributing/supporting_new_profiler.md, docs/contributing/taxpasta_profiler_support_overview.puml, pyproject.toml, src/taxpasta/application/service/profile_reader.py, src/taxpasta/domain/model/standard_profile.py, src/taxpasta/domain/model/tidy_observation_table.py, src/taxpasta/domain/model/wide_observation_table.py, src/taxpasta/infrastructure/application/bracken/bracken_profile.py, src/taxpasta/infrastructure/application/centrifuge/centrifuge_profile.py, src/taxpasta/infrastructure/application/diamond/diamond_profile.py, src/taxpasta/infrastructure/application/kaiju/kaiju_profile.py, src/taxpasta/infrastructure/application/kraken2/kraken2_profile.py, src/taxpasta/infrastructure/application/krakenuniq/krakenuniq_profile.py, src/taxpasta/infrastructure/application/megan6/megan6_profile.py, src/taxpasta/infrastructure/application/metaphlan/metaphlan_profile.py, src/taxpasta/infrastructure/application/metaphlan/metaphlan_profile_standardisation_service.py, src/taxpasta/infrastructure/application/motus/motus_profile.py, src/taxpasta/infrastructure/application/sample_sheet.py
=> Fix metaphlan tax ID being -1 and combine all unclassified counts

CHANGELOG.md, src/taxpasta/infrastructure/application/standard_profile_writer/arrow_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/ods_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/parquet_standard_profile_writer.py, src/taxpasta/infrastructure/application/standard_profile_writer/xlsx_standard_profile_writer.py, src/taxpasta/infrastructure/application/tidy_observation_table_writer/arrow_table_writer.py, src/taxpasta/infrastructure/application/tidy_observation_table_writer/ods_table_writer.py, src/taxpasta/infrastructure/application/tidy_observation_table_writer/parquet_table_writer.py, src/taxpasta/infrastructure/application/tidy_observation_table_writer/xlsx_table_writer.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/arrow_wide_observation_table_writer.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/biom_wide_observation_table_writer.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/ods_wide_observation_table_writer.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/parquet_wide_observation_table_writer.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/xlsx_wide_observation_table_writer.py, src/taxpasta/infrastructure/cli/merge.py, src/taxpasta/infrastructure/cli/standardise.py, src/taxpasta/infrastructure/domain/service/taxopy_taxonomy_service.py
=> Insert taxonomic information in a more suitable column order

CHANGELOG.md, docs/contributing/index.md, docs/index.md, docs/tutorials/.pages, docs/tutorials/deepdive.md, docs/tutorials/getting-started.md
=> Split up getting started to simplified version and deep dive

CHANGELOG.md, docs/quick_reference/merge_help.txt, docs/quick_reference/standardise_help.txt, src/taxpasta/infrastructure/cli/merge.py, src/taxpasta/infrastructure/cli/standardise.py
=> docs: improve description of options behavior

docs/commands/index.md, docs/commands/merge.md, docs/commands/standardise.md, docs/contributing/index.md, docs/how-tos/how-to-add-names.md, docs/how-tos/how-to-customise-sample-names.md, docs/index.md, docs/quick_reference/index.md, docs/supported_profilers/index.md, docs/tutorials/deepdive.md, docs/tutorials/getting-started.md, docs/tutorials/tutorial_python_snippets.md, docs/tutorials/tutorial_r_snippets.md
See answer to my question in the [mkdocs discussions](https://github.com/mkdocs/mkdocs/discussions/3230#discussioncomment-6020774).
=> WIP: fix links by using relative ones to markdown files

.gitignore, paper/paper.bib, paper/paper.md
Some further comments below, I still need to make suggestions on the statement of need
My read-through notes:
Questions:
=> Paper: Changes/suggations on affiliations/acknowledgements/summary

paper/paper.md
I added some first thoughts/suggestions.
=> Add first suggestions

paper/paper.bib, paper/paper.md
I have tried to improve upon James' suggestions. I've addressed some of his notes in #106. In particular, I've added a paragraph on OPAL.
I think we still need:
Let me know what you think about these changes 😃
=> Moritz review

paper/paper.md
A couple of very minor tweaks, but otherwise I think it is reasonable to go.
I could make ask for comments from my group if we want an informal peer-review of the paper?
=> Minor grammartical and phrasing fixes

paper/paper.md
As requested in editor comments: https://github.com/openjournals/joss-reviews/issues/5627#issuecomment-1626891804
1. Simplifies affiliations
2. Ensures consistent british spelling througout (just two cases as far as I can see manually, and also after an additional spell check run)
=> Address editor comments

CHANGELOG.md, src/taxpasta/infrastructure/domain/service/taxopy_taxonomy_service.py, tests/unit/infrastructure/domain/service/test_taxopy_taxonomy_service.py
=> Fix reverse lineage

src/taxpasta/domain/service/taxonomy_service.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/biom_wide_observation_table_writer.py, src/taxpasta/infrastructure/domain/service/taxopy_taxonomy_service.py, tests/system/cli/test_taxpasta_merge.py, tests/unit/infrastructure/domain/service/test_taxopy_taxonomy_service.py
=> Feat biom tax table

CHANGELOG.md, src/taxpasta/application/add_tax_info_command.py, src/taxpasta/infrastructure/cli/standardise.py, tests/integration/test_add_tax_info.py
=> fix: repair adding tax info to results

pyproject.toml, src/taxpasta/domain/service/taxonomy_service.py, src/taxpasta/infrastructure/application/wide_observation_table_writer/biom_wide_observation_table_writer.py, src/taxpasta/infrastructure/domain/service/taxopy_taxonomy_service.py, tests/unit/infrastructure/domain/service/test_taxopy_taxonomy_service.py, tox.ini
Lineages should now be properly aligned and output is mia compatible. This PR makes use of new features in taxopy 0.12 and improves lineage reporting. Additionally, the BIOM output now conforms with expectations from the R package mia.
=> feat: change output of BIOM format
